### ISSUE TITLE
Have this paper released?

### ISSUE THREAD

**Issue by xxAna** [seathiefwang/MGN-pytorch#21]
Thank you for your sharing. And I wonder if this paper have already released? I didn't find any relative informations on arxiv. Thank you again and waiting for your reply.

**Comment by seathiefwang** [comment]
https://arxiv.org/abs/1804.01438v1

**Comment by xxAna** [comment]
@seathiefwang Thank you for your reply. And sorry for my English expression. Actually, I was wonder whether this job be accepted by any publications? That is a good job.

**Comment by seathiefwang** [comment]
ACM Multimedia 2018， cvpr2018 missed。

**Comment by xxAna** [comment]
@seathiefwang Get it.Thank you again for your reply.
