### ISSUE TITLE
Test the model

### ISSUE THREAD

**Issue by TTMRonald** [seathiefwang/MGN-pytorch#4]
Hi, seathiefwang.
Your work is good, but I have a problem. If I just want to test this model on cpu, how do I need to modify demo.sh?

**Comment by seathiefwang** [comment]
You can add --cpu parameter.

**Comment by TTMRonald** [comment]
@seathiefwang 
If I just want to test the model_best.pt which you provided, how do I need to modify demo.sh? add --test_only parameter? where should the model_best.pt be placed?

**Comment by seathiefwang** [comment]
`python3 main.py --datadir ../reid-mgn/Market-1501-v15.09.15/ --margin 1.2 --save sgd_0 --cpu --test_only --resume 0 --pre_train experiment/sgd_0/model/model_best.pt`

**Comment by TTMRonald** [comment]
@seathiefwang 
thanks.

**Comment by hsdong2012** [comment]
Hi, seathiefwang
When I run the code, the following problem occurs:
TypeError: '<' not supported between instances of 'slice' and 'int'
I tracked the code, and find the it is invoked by the following line
res_conv4 = nn.Sequential(*resnet.layer3[1:])
could you help me to solve this problem?

the environment is as follows:
python 3.6, pytorch 0.4.1, torchvision, 0.21,

**Comment by chj1933** [comment]
@seathiefwang, 老师，你好！请问一下如果我用你的MGN训练好模型后，我要在另外一个数据集进行微调，应该怎么做？谢谢解答。

**Comment by seathiefwang** [comment]
@hsdong2012 Have you modified the code? I don't know this error, can I submit a complete error log?

**Comment by seathiefwang** [comment]
@chj1933 这个项目没有编写针对于其它数据集的加载数据集代码，如果你需要在其它数据集上进行训练，需要在data目录下仿照market1501.py编写数据加载代码。
